# Generated by Django 5.0.4 on 2024-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_razorpaytransaction_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RazorpayTransaction',
        ),
    ]
