# Generated by Django 5.0.4 on 2024-04-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_order_cgst_order_igst_order_sgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sgst',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
